# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit reco.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)


## ----fig1, out.width = "80%", out.height = "50%", fig.cap = "The daily downloads of R software (a) and R packages (b). The boxplots show the daily number of downloads in a month. The blue lines show the average daily download in each year, and the dashed red line indicates where the number of downloads shows a sudden change (yielded by changepoint package). Source of data: http://cran-logs.rstudio.com/. "----
knitr::include_graphics("fig1.png")


## ----fig2, out.width = "100%", out.height = "30%", fig.cap = "Framework of the R ecosystem in our study. This resembles the biological ecosystem which consists of three main roles, namely producers, consumers, and decomposers. "----
knitr::include_graphics("fig2.png")


## ----fig3, out.width = "100%", out.height = "30%", fig.cap = "Top 10 R packages (a) by total downloads and (b) by monthly downloads from 2005 to 2019 since publication. "----
knitr::include_graphics("fig3.png")


## ----fig4, out.width = "100%", out.height = "50%", fig.cap = "Usage of R in academia between 2005 and 2019. (a) Growth of academic articles citing R software. (b) The number of articles citing R software in different subject areas over time. (c) Top 10 subjects with most articles citing R software. (d) Top 10 subjects with the largest proportion of articles citing R software. The subject classification is based on the list of Scopus Subject Area (AGRI: Agricultural and Biological Sciences; ARTS: Arts and Humanities; BIOC: Biochemistry, Genetics, and Molecular Biology; BUSI: Business, Management, and accounting; CENG: Chemical Engineering; CHEM: Chemistry; COMP: Computer Science; DECI: Decision Sciences; DENT: Dentistry; EART: Earth and Planetary Sciences; ECON: Economics, Econometrics, and Finance; ENER: Energy; ENGI: Engineering; ENVI: Environmental Science; HEAL: Health Professionals; IMMU: Immunology and Microbiology; MATE: Materials Science; MATH: Mathematics; MEDI: Medicine; MULT: Multidisciplinary; NEUR: Neuroscience; NURS: Nursing; PHAR: Pharmacology, Toxicology, and Pharmaceutics; PHYS: Physics and Astronomy; PSYC: Psychology; SOCI: Social Sciences; VETE: Veterinary). "----
knitr::include_graphics("fig4.png")


## ----fig5, out.width = "100%", out.height = "40%", fig.cap = "Knowledge graph of R based on package description archived on CRAN. Only the top 50 keywords with the highest frequency are displayed. The width of an edge is proportional to the number of co-occurrences. The graph adopted a radial layout around a focal node wherein the most frequent keyword is selected as the focal node (namely 'data sets' with 539 occurrences). "----
knitr::include_graphics("fig5.png")


## ----fig6, out.width = "100%", out.height = "50%", fig.cap = "Collaboration patterns in R community. (a) Distribution of the number of authors of R packages (packages with more than 15 authors are omitted). (b) Correlation between the number of authors and the number of imported packages. (c) Correlation between the number of authors and the daily number of downloads. (d) Correlation between the number of authors and the number of updates per year. The legends show how many packages lie in the blocks. "----
knitr::include_graphics("fig6.png")


## ----fig7, out.width = "100%", out.height = "30%", fig.cap = "The driving models of the R ecosystem from different perspectives. (a) From the perspective of statistics. (b) From the perspective of computer science. (c) From the perspective of users. "----
knitr::include_graphics("fig7.png")

